---
# tasks file for change-motd
- name: Change MOTD
  copy: 
    content: " \n"
    dest: /etc/motd

- name: Disable the default MOTD
  file:
    dest: "/etc/update-motd.d/"
    mode: "u-x,g-x,o-x"
    state: directory
    recurse: yes
